In [6]:
import numpy as np

In [7]:
twoDArray = np.array([[11,15,10,6,],[10,14,11,5], [12,17,12,8], [15,18,14,9]])
print(twoDArray)

[[11 15 10  6]
 [10 14 11  5]
 [12 17 12  8]
 [15 18 14  9]]


In [10]:
newTwoDArray = np.insert(twoDArray,1,[[1,2,3,4]], axis=0)
print(newTwoDArray)

[[11 15 10  6]
 [ 1  2  3  4]
 [10 14 11  5]
 [12 17 12  8]
 [15 18 14  9]]


In [11]:
print(len(twoDArray))

4


In [12]:
newTwoDArray = np.append(twoDArray, [[1,2,3,4]], axis=0)
print(newTwoDArray)

[[11 15 10  6]
 [10 14 11  5]
 [12 17 12  8]
 [15 18 14  9]
 [ 1  2  3  4]]


In [14]:
print(len(newTwoDArray))

5


In [15]:
print(len(newTwoDArray[0]))

4


In [17]:
def accesElements(array,rowIndex, colIndex):
    if rowIndex >= len(array) and colIndex >= len(array[0]):
        print('incorrect index')
    else:
        print(array[rowIndex][colIndex])

In [20]:
accesElements(newTwoDArray,2,1)

17


In [23]:
def traverseDArray(array):
    for i in range(len(array)):
        for j in range(len(array[0])):
            print(array[i][j])

In [26]:
traverseDArray(twoDArray)

11
15
10
6
10
14
11
5
12
17
12
8
15
18
14
9


In [24]:
def searchTDArray(array,value):
    for i in range(len(array)):
        for j in range(len(array[0])):
            if array [i][j] == value:
                return 'The value is located index' + str(i)+" "+str(j)
    return 'The element no found'

In [25]:
print(searchTDArray(twoDArray,8))

The value is located index2 3


In [33]:
#0=untuk baris, 1=untuk kolom
newTDArray = np.delete(twoDArray, 2, axis=1)
print(newTDArray)

[[11 15  6]
 [10 14  5]
 [12 17  8]
 [15 18  9]]


In [28]:
print(twoDArray)

[[11 15 10  6]
 [10 14 11  5]
 [12 17 12  8]
 [15 18 14  9]]
